spring:
  application:
    name: BankApp
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/banking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  logging:
    export:
      otlp:
        enabled: false
  otlp:
    metrics:
      export:
        enabled: false
  tracing:
    export:
      otlp:
        enabled: false